Allison/4.2 (#61)
* REF/SM: Snap snapshot diff window to the right of the main.

* UI/SM: Update snapshot diff ui.

* REF/SM: Update stylesheet for ion source name labels.

* REF/SM: Align the column names for the exported CSV table.

* REF/SM: Adjust snapshot diff window width to the contents.

* REF/SM: Place a drop shadow to the ion icons.

* REF/SM: Format x0/y0 :.3g.

* FIX/AS: Initialize image data array as empty before each run, delayed start scan.

- suspect the establishing large array monitor take some time.
  - in Device.move(), delay the start scan in 1 second.
  - meanwhile, reinitialize the current_array variable, to avoid crash due to un-defined variable
    (AttributeError: 'AllisonScannerWindow' object has no attribute '_current_array' ...)

* REF/AS: Stop motor moving when aborting scan.

* REF/AS: Support stop motor moving via stop_move_btn.

* UI/AS: Add stop motor move button, add spinboxes for live scan config.

* REF/AS: Post the live scan config values to a new set of spinboxes.

* REF/AS: Stop unnecessary param sync before run, incl. scan conf to readiness check.

* REF/AS: Put 'jet' as the first favorite color map choice.

* REF/AS: Move the messagebox to the center after saving files.

* REF/AS: Add a button for opening the saved file.

* UI/AS: Add a test button.

* REF/AS: Add a test button.

* FIX/AS: Fix test button callback.

* REF/AS: Show message on the statusbar if failed estimating init noise level.

* FIX/AS: Do not check when data is actually receiving.

- as it is not reliable, on_update() may be skipped if happens.

* MNT/AS: Clean up.

* REF/AS: Delayed start scan in 10 ms instead of 1s.

* MNT/AS: Optimize imports.

* UI/AS: Update UI.

* REF/AS: Hide scan config track widgets.

* REF/AS: Do not push the read scan configs to device for offline mode.

- the scan configs for pos and volt are read from a file.

* REF/AS: Add a messagebox to explain interlock bypass option.

* REF/AS: Hide test button.