REF/SM: Convert number to string with 'str()'.
- when e.g. filter like "state=OFF" is enabled, take snapshot leads crashes, due to:

Traceback (most recent call last):
  File "/user/zhangt/development/phantasy-apps/phantasy_apps/settings_manager/utils.py", line 704, in filterAcceptsRow
    if not self.test_string_filters(src_row, src_model):
  File "/user/zhangt/development/phantasy-apps/phantasy_apps/settings_manager/utils.py", line 530, in test_string_filters
    if not self.test_one_string_filter(src_row, m_src, key, is_number_key, value):
  File "/user/zhangt/development/phantasy-apps/phantasy_apps/settings_manager/utils.py", line 547, in test_one_string_filter
    var = self.fmt.format(var)
AttributeError: '_SortProxyModel' object has no attribute 'fmt'

This commit fixed this issue.