FIX/AS: Initialize image data array as empty before each run, delayed start scan.
- suspect the establishing large array monitor take some time.
  - in Device.move(), delay the start scan in 1 second.
  - meanwhile, reinitialize the current_array variable, to avoid crash due to un-defined variable
    (AttributeError: 'AllisonScannerWindow' object has no attribute '_current_array' ...)